spring:
  jmx.enabled: false
  main:
    banner-mode: off
    lazy-initialization: true
  data.mongodb.uri: mongodb://mongodb/sledger

sledger:
  secret-key: x

logging.level:
  org:
    springframework:
      boot: ERROR
      data: ERROR
      context: ERROR
      security: ERROR
    apache: ERROR
    mongodb: ERROR
    testcontainers: ERROR
  org.springframework.core.LocalVariableTableParameterNameDiscoverer: ERROR
