spring:
  web.resources.add-mappings: false
  jmx.enabled: false
  main:
    banner-mode: off
    lazy-initialization: true
  data.mongodb:
    uri: ${MONGO_URI}
    auto-index-creation: true
  jackson.default-property-inclusion: non_null

sledger:
  uri: http://localhost:8080
  from-email: hello@sledger.tech
  secret-key: ${SLEDGER_SECRET_KEY}
  resend-key: ${SLEDGER_RESEND_KEY}

logging.level:
  org:
    springframework:
      boot: ERROR
      data: ERROR
      context: ERROR
      security: ERROR
    apache: ERROR
    mongodb: ERROR
    testcontainers: ERROR
  org.springframework.core.LocalVariableTableParameterNameDiscoverer: ERROR
