spring:
  jmx.enabled: false
  main:
    banner-mode: off
    lazy-initialization: true
  data.mongodb.uri: ${MONGO_URI}
  mail:
    host: localhost
    port: 3025
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp:
        auth: true
        connection-timeout: 25000
        timeout: 25000
        writeTimeout: 25000
        starttls.enable: true

sledger:
  uri: http://localhost:8080
  from-email: hello@sledger.tech
  secret-key: ${SLEDGER_SECRET_KEY}

management.health.mail.enabled: false

logging.level:
  org:
    springframework:
      boot: ERROR
      data: ERROR
      context: ERROR
      security: ERROR
    apache: ERROR
    mongodb: ERROR
    testcontainers: ERROR
  org.springframework.core.LocalVariableTableParameterNameDiscoverer: ERROR
