name: Pull Request

on:
  pull_request:
    types: [ opened, edited, reopened ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: 21

    - uses: gradle/gradle-build-action@v3
      with:
        arguments: build

    - uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
