name: Build and Release

on:
  push:
    branches: [ main ]
    paths:
      - '**.java'
      - '**.gradle'
      - '.github/workflows/**'

env:
  REPO: ${{ github.event.repository.name }}
  IMAGE_BASE: ${{ secrets.DOCKER_REGISTRY }}/${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    outputs:
      tag: ${{ steps.tag.outputs.nextStrict }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Setup GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '25'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5

    - name: Run tests
      run: ./gradlew test

    - name: Submit tests to CodeCov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - id: tag
      uses: ietf-tools/semver-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        noVersionBumpBehavior: patch
        noNewCommitBehavior: current

    - name: Setup Docker metadata
      run: |
        echo "IMAGE_NAME=${IMAGE_BASE}:${{ steps.tag.outputs.nextStrict }}" >> $GITHUB_ENV
        echo "DOCKER_USER=${{ secrets.DOCKER_USER }}" >> $GITHUB_ENV
        echo "DOCKER_PASS=${{ secrets.DOCKER_PASS }}" >> $GITHUB_ENV

    - name: Build native image
      run: ./gradlew bootBuildImage

  release:
    needs: build
    runs-on: on-prem
    environment: 'Prod'
    steps:
    - name: Perform rolling update
      run: |
        kubectl -n default set image deploy/${REPO} ${REPO}=${IMAGE_BASE}:${{ needs.build.outputs.tag }}
        kubectl -n default rollout status deploy/${REPO}
