name: Build and Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.new_tag }}
    steps:
    - uses: actions/checkout@v4

    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: '22'
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - uses: gradle/actions/setup-gradle@v3

    - id: tag
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: ''

    - run: echo "IMAGE_NAME=ghcr.io/${{github.repository}}:${{ steps.tag.outputs.new_tag }}" >> $GITHUB_ENV

    - run: echo "DOCKER_USER=${{ github.actor }}" >> $GITHUB_ENV

    - run: echo "DOCKER_PASS=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

    - run: ./gradlew build bootBuildImage --imageName $IMAGE_NAME --publishImage

    - uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  release:
    needs: build
    runs-on: self-hosted
    environment: 'Prod'
    env:
      DEPLOYMENT: ${{ github.event.repository.name }}
    steps:
    - name: Perform rolling update
      run: |
        kubectl set image deployment/${DEPLOYMENT} ${DEPLOYMENT}=${{ needs.build.outputs.tag }}
        kubectl rollout status deployment/${DEPLOYMENT}

    - uses: smartsquaregmbh/delete-old-packages@v0.8.0
      with:
        keep: 2
        type: container
        names: ${{ env.DEPLOYMENT }}
        token: ${{ secrets.GITHUB_TOKEN }}
        organization: ${{ github.event.organization.login }}
