name: Build and Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ env.IMAGE_NAME }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '22'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Run tests
      run: ./gradlew test

    - name: Submit tests to CodeCov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Generate new tag
      id: tag
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: ''

    - name: Setup Docker metadata
      env:
        DOCKER_USER: ${{ github.actor }}
        IMAGE_NAME: ghcr.io/${{github.repository}}:${{ steps.tag.outputs.new_tag }}
      run: |
        echo "::add-mask::${{ env.IMAGE_NAME }}"
        echo "::add-mask::${{ env.DOCKER_USER }}"
        echo "IMAGE_NAME=${{ env.IMAGE_NAME }}" >> $GITHUB_ENV
        echo "DOCKER_USER=${{ env.DOCKER_USER }}" >> $GITHUB_ENV
        echo "DOCKER_PASS=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

    - name: Build native image
      run: ./gradlew bootBuildImage

  release:
    needs: build
    runs-on: on-prem
    environment: 'Prod'
    env:
      DEPLOYMENT: ${{ github.event.repository.name }}
    steps:
    - name: Perform rolling update
      run: |
        kubectl set image deployment/${DEPLOYMENT} ${DEPLOYMENT}=${{ needs.build.outputs.image_name }} -n default
        kubectl rollout status deployment/${DEPLOYMENT} -n default

    - name: Delete old packages
      uses: smartsquaregmbh/delete-old-packages@v0.8.0
      with:
        keep: 2
        type: container
        names: ${{ env.DEPLOYMENT }}
        token: ${{ secrets.GITHUB_TOKEN }}
        organization: ${{ github.event.organization.login }}
